[build]
  command = "npm run build"
  publish = ".next/static"
  functions = ".next/server"

[[plugins]]
  package = "@netlify/plugin-nextjs@4.0.0"  # Specify latest version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true